### ISSUE TITLE
Simple Login doesnt work

### ISSUE THREAD

**Issue by TobiasWeiseX** [fmenabe/python-dokuwiki#16] opened 2019-07-20 17:29 UTC
```python
import dokuwiki

try:
    url = "http://my.page.com/dokuwiki"
    nick = "myname"
    pwd = "mypwd"
    wiki = dokuwiki.DokuWiki(url, nick, pwd)
    html = wiki.pages.html('start')
    print(html)

except (dokuwiki.DokuWikiError, Exception) as err:
    print('unable to connect: %s' % err)

```

gives me Exception

**unable to connect: invalid login or password!**

while

```python
from xmlrpc.client import ServerProxy
from urllib.parse import urlencode

URL = "http://my.page.com/dokuwiki"
USER = "myname"
PWD = "mypwd"

url = '%s/lib/exe/xmlrpc.php?%s' % (URL, urlencode({'u': USER, 'p': PWD}))
proxy = ServerProxy(url)
print(proxy.dokuwiki.getVersion())
# should print something like: Release 2018-04-22b "Greebo"

for x in proxy.dokuwiki.search('start'):
    print(x["snippet"])
    break

```

does everything i want...

Any idea what this could be?

**Comment by fmenabe** [comment] 2019-07-22 15:24
[duplicate of #15]

It seems that on some configuration, calling the XMLRPC ``dokuwiki.login`` method return *False*. This call is done in the constructor because it is required for cookie based authentication and it allows to ensure the connection is working (an error is thrown when initializing the object and not at the fisrt call). 
By default, username and password are passed in the URI, so the call to ``login`` should always return *True* ...  Just to confirm, from the snippet code, can you show the result of (should return *True* but seem to fail) :

```print(proxy.dokuwiki.login(USER, PWD))```
<br/>

I pushed a commit in the [login](https://github.com/fmenabe/python-dokuwiki/tree/login) branch of the repo that remove the call to the login method in the constructor. Can you test this branch and confirm it now works for you?

Before merging the branch and releasing a new version, I'm still curious about why the call to the ``login`` method fail. Do you have any Captcha or redirect configured server-side? Can you also test cookie authentication (this will probably fail but may give clues of what's wrong):

```wiki = dokuwiki.DokuWiki(URL, USER, PWD, cookieAuth=True)```

**Comment by TobiasWeiseX** [comment] 2019-07-23 21:03
`print(proxy.dokuwiki.login(USER, PWD))`

returns **False**.

`wiki = dokuwiki.DokuWiki(URL, USER, PWD, cookieAuth=True)`

ends in the same **unable to connect: invalid login or password!** error

I don't use any Captcha or redirect configured server-side.

Oh and login branch works.

**Comment by fmenabe** [comment] 2019-07-24 16:53
I just release a new version (*1.2.1*) on PyPI.

**Closed by fmenabe** 2019-07-24 16:53 UTC
